In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('Weather.csv')

In [6]:
#Top 5 elements of the data
df.head()

STA      Date Precip  WindGustSpd    MaxTemp    MinTemp   MeanTemp  \
0  10001  7/1/1942  1.016          NaN  25.555556  22.222222  23.888889   
1  10001  7/2/1942      0          NaN  28.888889  21.666667  25.555556   
2  10001  7/3/1942   2.54          NaN  26.111111  22.222222  24.444444   
3  10001  7/4/1942   2.54          NaN  26.666667  22.222222  24.444444   
4  10001  7/5/1942      0          NaN  26.666667  21.666667  24.444444   

  Snowfall PoorWeather  YR  ...  FT  FB FTI  PGT  TSHDSBRSGF  SD3  RHX  RHN  \
0        0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
1        0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
2        0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
3        0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   
4        0         NaN  42  ... NaN NaN NaN  NaN         NaN  NaN  NaN  NaN   

  RVG  WTE  
0 NaN  NaN  
1 NaN  NaN  
2 NaN  NaN  
3 NaN  NaN  
4 NaN  NaN  

[5 rows x 30 columns]

In [7]:
#Bottom 5 elements
df.tail()

STA        Date Precip  WindGustSpd    MaxTemp    MinTemp  \
119035  82506  12/27/1945      0          NaN  28.333333  18.333333   
119036  82506  12/28/1945  9.906          NaN  29.444444  18.333333   
119037  82506  12/29/1945      0          NaN  28.333333  18.333333   
119038  82506  12/30/1945      0          NaN  28.333333  18.333333   
119039  82506  12/31/1945      0          NaN  29.444444  17.222222   

         MeanTemp Snowfall PoorWeather  YR  ...  FT  FB FTI  PGT  TSHDSBRSGF  \
119035  23.333333        0         NaN  45  ... NaN NaN NaN  NaN         NaN   
119036  23.888889        0           1  45  ... NaN NaN NaN  NaN           1   
119037  23.333333        0           1  45  ... NaN NaN NaN  NaN           1   
119038  23.333333        0         NaN  45  ... NaN NaN NaN  NaN         NaN   
119039  23.333333        0         NaN  45  ... NaN NaN NaN  NaN         NaN   

        SD3  RHX  RHN RVG  WTE  
119035  NaN  NaN  NaN NaN  NaN  
119036  NaN  NaN  NaN NaN  NaN  
119037  NaN  NaN  NaN NaN  NaN  
119038  NaN  NaN  NaN NaN  NaN  
119039  NaN  NaN  NaN NaN  NaN  

[5 rows x 30 columns]

In [8]:
df.shape

(119040, 30)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119040 entries, 0 to 119039
Data columns (total 30 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   STA          119040 non-null  int64  
 1   Date         119040 non-null  object 
 2   Precip       119040 non-null  object 
 3   WindGustSpd  532 non-null     float64
 4   MaxTemp      119040 non-null  float64
 5   MinTemp      119040 non-null  float64
 6   MeanTemp     119040 non-null  float64
 7   Snowfall     117877 non-null  object 
 8   PoorWeather  34237 non-null   object 
 9   YR           119040 non-null  int64  
 10  MO           119040 non-null  int64  
 11  DA           119040 non-null  int64  
 12  PRCP         117108 non-null  object 
 13  DR           533 non-null     float64
 14  SPD          532 non-null     float64
 15  MAX          118566 non-null  float64
 16  MIN          118572 non-null  float64
 17  MEA          118542 non-null  float64
 18  SNF          117877 non-

In [10]:
#Problem Statement - Given a set of feature/s we have to estimate maximum temperature

In [19]:
#Independent Variable/Feature/Column
X = df[['MinTemp']]

In [24]:
X.isna().apply(pd.value_counts).T

False
MinTemp  119040

In [21]:
X.head()

MinTemp
0  22.222222
1  21.666667
2  22.222222
3  22.222222
4  21.666667

In [17]:
y = df[['MaxTemp']]

In [25]:
y.isna().apply(pd.value_counts).T

False
MaxTemp  119040

In [18]:
y.head()

MaxTemp
0  25.555556
1  28.888889
2  26.111111
3  26.666667
4  26.666667

In [23]:
#Importing Train Test Split
from sklearn.model_selection import train_test_split

In [65]:
#Train_Test_split - 70:30
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,train_size=0.7,random_state=1)

In [66]:
print(X_train.shape)

(83328, 1)


In [67]:
X_test.shape

(35712, 1)

In [68]:
df.shape

(119040, 30)

In [69]:
y_train.shape

(83328, 1)

In [70]:
y_test.shape

(35712, 1)

In [71]:
y_train.head()

MaxTemp
28674   30.000000
104390  30.000000
98796   28.333333
36857   30.000000
43000   11.666667

In [72]:
#Importing Linear Regression
#Our 1st ML Model
from sklearn.linear_model import LinearRegression

In [73]:
#Create an object class of Linear Regression
#Create a model for Linear Regression
model = LinearRegression()

In [74]:
#Train the model or make the model learn and calculate Linear Regresssion
model.fit(X_train,y_train)

LinearRegression()

In [75]:
#Test/Predict the data -> y_pred = yhat
y_pred = model.predict(X_test)

In [76]:
y_pred

array([[20.88972865],
       [28.56451499],
       [31.63442954],
       ...,
       [31.12277711],
       [28.56451499],
       [31.12277711]])

In [81]:
y_test = y_test.reshape(-1,1)
y_test

array([[29.44444444],
       [32.77777778],
       [37.22222222],
       ...,
       [32.77777778],
       [30.        ],
       [28.88888889]])

In [96]:
#Coefficent of x/Slope/Gradient of x
model.coef_

array([[0.92097436]])

In [97]:
#Intercept - C
model.intercept_

array([10.65668019])

In [82]:
#Comparing the actual and predicted observations
df_comp = pd.DataFrame({'Actual_MaxTemp':y_test.flatten(),'Predicted_MaxTemp':y_pred.flatten()})

In [83]:
df_comp

Actual_MaxTemp  Predicted_MaxTemp
0           29.444444          20.889729
1           32.777778          28.564515
2           37.222222          31.634430
3           33.333333          30.611125
4           30.000000          32.146082
...               ...                ...
35707       37.222222          21.401381
35708       27.222222          30.099472
35709       32.777778          31.122777
35710       30.000000          28.564515
35711       28.888889          31.122777

[35712 rows x 2 columns]

In [84]:
df_comp.to_csv('Predictions_Dcodr.csv')

In [86]:
df_comp.to_excel('Prediction_Dcodr.xlsx')

In [89]:
#Performance Metrics/Measures
#Accuracy for Regression Analysis
model.score(X_test,y_test)*100 #-> R Square

76.58019339654669

In [95]:
#Calculating R Square
from sklearn import metrics
metrics.r2_score(y_test,y_pred)*100

76.58019339654669

In [98]:
#Mean Squared Error
metrics.mean_squared_error(y_test,y_pred)

17.560811008066533